baseURL = 'https://blog.ramadio.com/'
languageCode = 'en-us'
title = 'Ramadio'
theme = 'paper'




[params]
  color = 'linen'

  twitter = 'riza_ramadan'
  github = 'rizaramadan'

  avatar = 'rizaramadan@gmail.com'
  name = 'Ramad'
  bio = 'Writing about work related'

[services]
  [services.googleAnalytics]
    ID = 'G-Y0RE36EK2Y'